# This file was generated by GoReleaser. DO NOT EDIT.
cask "json2go" do
  name "json2go"
  desc "json2go is a tool to convert JSON to Go struct."
  homepage "https://github.com/winebarrel/json2go"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "json2go"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_darwin_amd64.tar.gz"
      sha256 "91599745815135254e5d7b27a5eaf75e3dc5685c1ca6639b528d98a02c9daa3a"
    end
    on_arm do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_darwin_arm64.tar.gz"
      sha256 "5f74de81d5934cfb35e0a29078991163de8dd7f12687becdc25a565170241ba1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_linux_amd64.tar.gz"
      sha256 "433cfcd3e3055f688e875aba6575b30b8e151fdbe30d39b18fd5572ecb190936"
    end
    on_arm do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_linux_arm64.tar.gz"
      sha256 "f3c150423eb036db7c48b16ee8eb9c2e57a830641fe113fd0f8899011eaa6e76"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/json2go"]
    end
  end

  # No zap stanza required
end
