# This file was generated by GoReleaser. DO NOT EDIT.
cask "json2go" do
  name "json2go"
  desc "json2go is a tool to convert JSON to Go struct."
  homepage "https://github.com/winebarrel/json2go"
  version "2.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "json2go"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_darwin_amd64.tar.gz"
      sha256 "e945706df165d6b7077002342310bd09b006fb72b07e173df38489a25e0e7fa6"
    end
    on_arm do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_darwin_arm64.tar.gz"
      sha256 "66fb30a696b8c41db7eef1844cbdffcdd6dd8e544a9d5d729fa4ed1b66d33fd8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_linux_amd64.tar.gz"
      sha256 "1c34761e7e6cadff7d32908b2969372a290c7e83f9d9f3b96e5b5a0efaeaf91f"
    end
    on_arm do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_linux_arm64.tar.gz"
      sha256 "0c104e1eb7ca3ec89295f1999b272f093244ffc3e6fdacec8f375e99f3e0e724"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/json2go"]
    end
  end

  # No zap stanza required
end
