# This file was generated by GoReleaser. DO NOT EDIT.
cask "json2go" do
  name "json2go"
  desc "json2go is a tool to convert JSON to Go struct."
  homepage "https://github.com/winebarrel/json2go"
  version "2.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "json2go"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_darwin_amd64.tar.gz"
      sha256 "b51013a879ab78d387cc3a63e44f29a1ed08ae635cce67484cb682393ef0b9ef"
    end
    on_arm do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_darwin_arm64.tar.gz"
      sha256 "8a7263862129e245cbd1c219df9be27c00594feadaa2819671e1b2f29c19518d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_linux_amd64.tar.gz"
      sha256 "d3a0839ad34798dc21453b3a8e07ae25fb401a2b4430c950ede2c7bb1e0c117e"
    end
    on_arm do
      url "https://github.com/winebarrel/json2go/releases/download/v#{version}/json2go_#{version}_linux_arm64.tar.gz"
      sha256 "35ababec15150480d753e6b8fbaa78ab01ac616956cb6bd72b8d8107d5995d1e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/json2go"]
    end
  end

  # No zap stanza required
end
